#!/usr/bin/env node

var program = require('commander');
var chalk = require('chalk');
var shell = require('shelljs');
var _ = require('lodash');
const readline = require('readline');
const _pwd = shell.pwd();
const dirs = require('./constants').DIRS;

program.parse(process.argv);

function react_native_installed() {
	var check = shell.exec("react-native -v", {silent: true});
	if(check.code === 127) {
		return false;
	}
	return true;
}

function inside_react_native_dir() {
	var check = shell.exec("react-native -v", {silent: true});
	if(check.code === 0 && check.output.match(/not inside/) === null) {
		return true;
	}
	return false;
}

function log_path_exists(path) {
	shell.echo(chalk.bold.red('exists ') + chalk.bold(path));
}

function log_path_created(path) {
	shell.echo(chalk.green('mkdir ') + chalk.bold.green(path));
}

function generate_dirs() {
	_.forEach(dirs, function(val, key) {
		file_path = val;

		if(shell.test('-e', file_path)) {
			log_path_exists(file_path);
		}	else {
			shell.mkdir('-p', file_path);
			log_path_created(file_path);
		}
	});
}

function generate_react_native(name) {
	var com = shell.exec('react-native init ' + name);
	shell.cd(_pwd + '/' + name);
}

function onErr(err) {
  console.log(err);
  return 1;
}

function main() {
	if(!react_native_installed()) {
		shell.echo('Please install react-native-cli before using rng');
		process.exit(1);
	}

	if(program.args.length === 1) {
		var app_name = program.args[0];
		console.log("App name " + app_name);

		if(inside_react_native_dir()) {
			shell.echo(chalk.yellow("You're already inside a react-native app"));
		} else {
			shell.echo(chalk.bold("Generating react native and rng structure..."));
			//generate the whole react-native app and cd into it
			generate_react_native(app_name);
		}

		generate_dirs();
		process.exit(0);
	} else if (program.args.length > 1) {
		shell.error(chalk.red("Passing too many arguments !!!"));
		process.exit(1);
	} else {
		if(!inside_react_native_dir()) {
			//generate react-native app
			console.log("You're not inside a react-native app and did not give a name for it");
			console.log("Please enter a name for you react-native app");
      const rl = readline.createInterface({
      	input: process.stdin,
  			output: process.stdout
      });
      rl.question('App name: ', (answer) => {
  			console.log(chalk.bold("Generating " + answer +" app"));
  			generate_react_native(answer);
  			generate_dirs();
  			rl.close();
  			process.exit(0);
			});
		}
	}
}

main();
