#!/usr/bin/env node

var program = require('commander');
var chalk = require('chalk');
var _ = require('lodash');

program
	.action(function() {
		console.log("Creating component(s)...");
	})
	.parse(process.argv);

var component_names = program.args;

if (!component_names.length) {
  console.error('Component name required');
  process.exit(1);
}

_(component_names).forEach(function(component) {
	if(typeof component === "string") {
		console.log(chalk.bold("Created component with name: ") + chalk.green(_.capitalize(component)));
	}
});
