#!/usr/bin/env node
const dirs = require('./constants').DIRS;
var program = require('commander');
var chalk = require('chalk');
var _ = require('lodash');
var shell = require('shelljs');
var FileGenerator = require('./modules/FileGenerator');

program.parse(process.argv);

var component_names = program.args;

if (!component_names.length) {
  console.error(chalk.bold.red('Component name required'));
  process.exit(1);
}

_(component_names).forEach(function(component) {
	FileGenerator.generate_component_file(component);
	FileGenerator.generate_style_file(component);
});
